favorites/urls.py
"""URL of favorites app"""
from django.urls import path

from . import views

app_name = 'favorites'
urlpatterns = [
    path(
        'addfavorites/',
        views.FavoriteCreateView.as_view(),
        name='add_favorites'
    ),
    path('welldone/', views.WellDoneView.as_view(), name='well_done'),
    path('fail/', views.FailView.as_view(), name='fail'),
    path('myfavorites/', views.FavoriteListView.as_view(), name='my_favorites')
    ]

products/urls.py
"""URLS of products app"""
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product'),
    path('results/', views.ResultsListView.as_view(), name='results'),
    path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
    ]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('favorites/', include('favorites.urls'))
]

users/urls.py
"""Urls of user app, all urls that concern user
(authentification and others things)"""

from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('my_account/', views.UserDetailView.as_view(), name='user_account'),
    path('sign_in/', views.SignIn.as_view(), name='sign_in')
]

website/urls.py
"""URLS of website app"""
from django.urls import path

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('legal_mentions/', views.legal_mentions, name='legal_mentions'),
]

favorites/models.py
"""Models of favorites app"""
from django.db import models
from django.conf import settings


class Favorite(models.Model):
    """Favorites association object
    between user, product and other product"""

    # Fields
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="favorites")

    product = models.ForeignKey(
        'products.Product',
        on_delete=models.CASCADE,
        related_name="favorites_as_product",
    )
    substitute = models.ForeignKey(
        'products.Product',
        on_delete=models.CASCADE,
        related_name="favorites_as_substitute",
    )

    def __str__(self):
        """Print attribute as title's object in Django admin"""
        return '%s, %s' % (self.user.username, self.substitute.name)

favorites/forms.py
"""Forms of favorites app"""
from django import forms

from .models import Favorite
from products.models import Product
from django.core.exceptions import ValidationError


class FavoriteForm(forms.Form):
    """Form to add Favorites objects in favorite user list"""
    product = forms.IntegerField(widget=forms.HiddenInput(), required=True)
    substitute = forms.IntegerField(widget=forms.HiddenInput(), required=True)

    def clean_product(self):
        """Return the Product object since the id input
        by user, if it exists"""
        product_id = self.cleaned_data['product']
        try:
            product = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            raise forms.ValidationError("Ce produit n'existe pas !")

        return product

    def clean_substitute(self):
        """Return the Product object (here the substitute)
        since the id input by user, if it exists"""
        substitute_id = self.cleaned_data['substitute']
        try:
            substitute = Product.objects.get(id=substitute_id)
        except Product.DoesNotExist:
            raise forms.ValidationError("Ce produit n'existe pas !")

        return substitute

    def save(self, user, commit=True):
        """Save the object Favorite build by
        user's profil and the products input by user"""
        product = self.cleaned_data['product']
        substitute = self.cleaned_data['substitute']
        favorite = Favorite(
            user=user, product=product, substitute=substitute
        )
        if commit:
            favorite.save()
        return favorite

favorites/views.py
"""Views of favorites app"""
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render

from .forms import FavoriteForm
from .models import Favorite


class FavoriteListView(LoginRequiredMixin, generic.ListView):
    """Favorites objects generic class-based view of a user"""
    model = Favorite
    template_name = 'favorites/favoritebyuser_list.html'

    def get_context_data(self, **kwargs):
        """Generic method to construct context for template"""
        context = super().get_context_data(**kwargs)

        list_favorites = Favorite.objects.filter(user=self.request.user)

        context['list_favorites'] = list_favorites

        return context


class FavoriteCreateView(LoginRequiredMixin, generic.View):
    """Generic class-based view to add Favorite objects in
    database"""

    def post(self, request):
        """Method POST data to FavoriteForm"""
        form = FavoriteForm(request.POST)
        if form.is_valid():
            form.save(request.user)
            return redirect('favorites:well_done')
        return redirect('favorites:fail')


class WellDoneView(LoginRequiredMixin, generic.View):
    """View to print favorite well added to database"""

    def get(self, request):
        """Method GET to print well done message"""
        context = {'msg_welldone': 'Produit ajouté à vos favoris !'}

        return render(request, 'favorites/well_done.html', context)


class FailView(LoginRequiredMixin, generic.View):
    """View listing to print favorite not added to database"""

    def get(self, request):
        """Method GET to print fail message"""
        context = {'msg_fail': 'Produit pas ajouté à vos favoris !'}

        return render(request, 'favorites/fail.html', context)

favorites/templates/favorites/fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Favoris</title>
</head>
{% extends "base.html" %}

{% block content %}
<!-- Masthead-->
<header class="masthead-s">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-11 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">{{ msg_fail }}</h1>
                <hr class="divider my-4" />
        </div>
    </div>
    </div>
</header>
<br >
<br >
<div class="container" id="fail">
  <div class="row justify-content-around">
    <div class="col-2 offset-md-1">
      <h3><a class="btn btn-default btn-lg" href="{% url 'website:index'%}">Faire une nouvelle recherche</a></h3>
    </div>
    <div class="col-2">
      <h3><a class="btn btn-default btn-lg" href="{% url 'favorites:my_favorites' %}">Aller dans mes favoris</a></h3>
    </div>
  </div>
</div>
{% endblock content %}

favorites/templates/favorites/favoritebyuser_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Favoris</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}
<!-- Masthead-->
<header class="masthead-s">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-11 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Vos Favoris</h1>
                <hr class="divider my-4" />
        </div>
    </div>
</header>
<br />
<br />
  {% if list_favorites %}
    <div class="container">
    <h1>Voici ce qui est bon pour la santé !</h1>
    <div class="row align-items-center">
        {% for product in list_favorites %}
        <div class="col product_list">
            <figure>
                <h3 class="nutriscore">{{ product.substitute.nutriscore }}</h3>
                <a id="results" href="{% url 'products:product' product.substitute.pk %}">
                <img class="results" src="{{ product.substitute.image_url }}" />
                </a>
                <a href="{% url 'products:product' product.pk %}">
                    <p>Pour remplacer : {{ product.product.name}}</p>
                </a>
            </figure>
        </div>
        {% endfor %}
        </div>
  {% else %}
    <h1>Il n'y aucun substitut pour ce produit !</h1>
  {% endif %}
{% endblock %}
</body>

favorites/templates/favorites/well_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Favoris</title>
</head>
{% extends "base.html" %}

{% block content %}
<!-- Masthead-->
<header class="masthead-s">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-11 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">{{ msg_welldone }}</h1>
                <hr class="divider my-4" />
        </div>
    </div>
    </div>
</header>
<br >
<br >
<div class="container" id="well">
  <div class="row justify-content-around">
    <div class="col-2 offset-md-1">
      <h3><a class="btn btn-default btn-lg" href="{% url 'website:index'%}">Faire une nouvelle recherche</a></h3>
    </div>
    <div class="col-2">
      <h3><a class="btn btn-default btn-lg" href="{% url 'favorites:my_favorites' %}">Aller dans mes favoris</a></h3>
    </div>
  </div>
</div>
{% endblock content %}