favorites/urls.py
"""URL of favorites app"""
from django.urls import path

from . import views

app_name = 'favorites'
urlpatterns = [
    path(
        'addfavorites/',
        views.FavoriteCreateView.as_view(),
        name='add_favorites'
    ),
    path('welldone/', views.WellDoneView.as_view(), name='well_done'),
    path('fail/', views.FailView.as_view(), name='fail'),
    path('myfavorites/', views.FavoriteListView.as_view(), name='my_favorites')
    ]

products/urls.py
"""URLS of products app"""
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product'),
    path('results/', views.ResultsListView.as_view(), name='results'),
    path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
    ]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('favorites/', include('favorites.urls'))
]

users/urls.py
"""Urls of user app, all urls that concern user
(authentification and others things)"""

from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('my_account/', views.UserDetailView.as_view(), name='user_account'),
    path('sign_in/', views.SignIn.as_view(), name='sign_in')
]

website/urls.py
"""URLS of website app"""
from django.urls import path

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('legal_mentions/', views.legal_mentions, name='legal_mentions'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'dist/assets/img/logo_pur_beurre-favicon.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'dist/css/styles.css'%}" rel="stylesheet" />
        <!-- JQuery-ui-->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <img id="logo" src="{% static 'dist/assets/img/logo_pur_beurre.png' %}" width="50" height="50"/>
                <a class="navbar-brand js-scroll-trigger" href="{% url 'website:index' %}"> Pur Beurre</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item">
                            <form method="get" action="{% url 'products:results' %}">
                            {{ substitute_form }}
                            </form>
                        </li>
                        <li class="nav-item"><a id="button-favorites" class="nav-link js-scroll-trigger" href="{% url 'favorites:my_favorites' %}">
                            <i class="fas fa-carrot"></i>
                        </a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a id="button-account" class="nav-link js-scroll-trigger" href="{% url 'users:user_account' %}">
                                <i class="fas fa-users"></i>
                            </a>
                            </li>
                            <li class="nav-item"><a id="button-logout" class="nav-link js-scroll-trigger" href="{% url 'logout' %}">
                                <i class="fas fa-sign-out-alt"></i>
                            </a>
                            </li>
                        {% else %}
                            <li class="nav-item"><a id="button-login" class="nav-link js-scroll-trigger" href="{% url 'login' %}">
                                <i class="fas fa-sign-in-alt"></i>
                            </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% endblock nav %}


        <!-- Content-->
        {% block content %}
        {% endblock content %}
    </body>
        <!-- Footer-->
        {% block footer %}
        <footer class="bg-light py-5">
            <div class="container">
                <div class="row justify-content-around">
                    <div class="col-2 offset-md-1">
                        <a href="{% url 'website:legal_mentions' %}">Mentions légales</a>
                    </div>
                    <div class="col-2">
                        <a href="{% url 'website:index' %}#contact ">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        {% endblock footer %}

        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'dist/js/scripts.js'%}"></script>
        <!-- JQuery-ui-->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
        <!-- Autocompletion-->
        <script>
        $("input[name=research]").autocomplete({
                source: "{% url 'products:autocomplete' %}",
                minLength: 2,
        });
        </script>
</html>