favorites/urls.py
"""URL of favorites app"""
from django.urls import path

from . import views

app_name = 'favorites'
urlpatterns = [
    path(
        'addfavorites/',
        views.FavoriteCreateView.as_view(),
        name='add_favorites'
    ),
    path('welldone/', views.WellDoneView.as_view(), name='well_done'),
    path('fail/', views.FailView.as_view(), name='fail'),
    path('myfavorites/', views.FavoriteListView.as_view(), name='my_favorites')
    ]

products/urls.py
"""URLS of products app"""
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product'),
    path('results/', views.ResultsListView.as_view(), name='results'),
    path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
    ]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('favorites/', include('favorites.urls'))
]

users/urls.py
"""Urls of user app, all urls that concern user
(authentification and others things)"""

from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('my_account/', views.UserDetailView.as_view(), name='user_account'),
    path('sign_in/', views.SignIn.as_view(), name='sign_in')
]

products/models.py
"""Models of products app"""
from django.db import models


class Category(models.Model):
    """Products Categories"""

    # Fields
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """Print attribute as title's object in Django admin"""
        return self.name


class Product(models.Model):
    """Products with a name, description, nutriscore
    categories, url on page product of OpenFoodFacts,
    image url from OpenFoodFacts and nutrition image url
    from OpenFoodFacts"""

    # Fields
    name = models.CharField('product name', max_length=100)
    description = models.TextField('product description')
    nutriscore = models.CharField('product nutriscore', max_length=1)
    categories = models.ManyToManyField('Category', related_name='products')
    url = models.URLField('product url')
    image_url = models.URLField('product image url')
    nutrition_image_url = models.URLField('product nutrition image url')

    def __str__(self):
        """Print attribute as title's object in Django admin"""
        return self.name

products/forms.py
"""Forms of products app"""
from django import forms


class SubstituteForm(forms.Form):
    """Form that send a product to find his substitutes
    (product with a better nutriscore than the product
    requested)"""
    research = forms.CharField(max_length=100,
                               label='',
                               widget=forms.TextInput(
                                   attrs={'placeholder': 'nutella'}
                                )
                               )

products/views.py
"""Views of products app, all views that concern products"""

from django.http import JsonResponse
from django.views import generic
from django.db.models import Count

from .models import Product


class ResultsListView(generic.ListView):
    """Generic class-based view listing all products by nutriscore"""
    model = Product
    template_name = 'products/results.html'

    def get_context_data(self, **kwargs):
        """Methods that return an enriched context to use for the view"""
        search_product = self.request.GET.get('research')
        context = super().get_context_data(**kwargs)

        list_product = Product.objects.filter(name__icontains=search_product)

        if not list_product:
            context['base_product'] = (
                'Oups ! Pas de meilleur produit que celui-ci.'
            )
        else:
            product = list_product[0]
            context['base_product'] = product

            # Take the categories of the researched product
            product_categories = product.categories.all()

            products = Product.objects.filter(
                nutriscore__lt=product.nutriscore
            )

            # Return all the objects of the categories of
            # the researched product order by nutriscore
            context['results'] = (
                products.filter(
                    categories__in=product_categories
                )
                .annotate(
                    num_categories_share_with_product=Count('categories')
                )
                .order_by('num_categories_share_with_product')
                .order_by('nutriscore')
                [:6]
            )
            return context

        return context


class ProductDetailView(generic.DetailView):
    """Generic class-based view detailed all products"""
    model = Product


class AutocompleteView(generic.View):
    """Generic class-based view to
    help user to find his product to replace
    with an autocomplete mechanism"""

    def get(self, request):
        """Method to apply autocomplete
        mechanism in case of only get method"""
        searched_term = request.GET.get("term")
        research = (
            Product.objects
            .filter(name__startswith=searched_term)
            .order_by('-nutriscore')
                    )
        results = []
        for r in research:
            results.append(r.name)
        return JsonResponse(results, safe=False)

products/templates/products/product_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ product.name }}</title>
</head>
<body>

{% block content %}
<header class="header">
    <div class="product_image" style="background-image: url({{ product.image_url }});">
    </div>
    <div class="product_name"><h1>{{ product.name }}</h1></div>
</header>
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Nutriscore</h1>
            {% if product.nutriscore == 'a' %}
            <h2>A</h2>
            {% else %}
            <h4>A</h4>
            {% endif %}
            {% if product.nutriscore == 'b' %}
            <h2>B</h2>
            {% else %}
            <h4>B</h4>
            {% endif %}
            {% if product.nutriscore == 'c' %}
            <h2>C</h2>
            {% else %}
            <h4>C</h4>
            {% endif %}
            {% if product.nutriscore == 'd' %}
            <h2>D</h2>
            {% else %}
            <h4>D</h4>
            {% endif %}
            {% if product.nutriscore == 'e' %}
            <h2>E</h2>
            {% else %}
            <h4>E</h4>
            {% endif %}
            </div>
        <div class="col">
            <h1>Repère nutritionnels pour 100g</h1>
            <img src="{{ product.nutrition_image_url }}" />
        </div>
        </div>
    <div class="off">
        <button class="btn btn-default btn-lg">
            <a href="{{ product.url }}"></a>
            <h1>Voir la fiche d'Open Food Facts</h1>
        </button>
    </div>
    </div>
</div>
{% endblock %}
</body>
</html>

products/templates/products/productsbycategory_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

products/templates/products/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page de résultats</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}
<!-- Masthead-->
<header class="header">
    <div class="product_image" style="background-image: url({{ base_product.image_url }});">
    </div>
    <div class="product_name"><h1>{{ base_product }}</h1></div>
</header>
<br />
<br />
  {% if results %}
    <div class="container">
    <h1>Vous pouvez remplacer cet aliment par :</h1>
    <div class="row align-items-center">
        {% for product in results %}
        <div class="col product_list">
            <figure>
                <h3 class="nutriscore">{{ product.nutriscore }}</h3>
                <a id="results" href="{% url 'products:product' product.pk %}">
                    <img class='results' src="{{ product.image_url }}" /></a>

                <form method="POST" action="{% url 'favorites:add_favorites' %}">
                    {% csrf_token %}
                    <button name="button-add-favorites" value="submit" class="btn btn-default btn-lg"><i class="far fa-save"></i>Sauvegarder</button>
                    <input type="hidden" name="product" value="{{ base_product.id }}"/>
                    <input type="hidden" name="substitute" value="{{ product.id }}"/>
                </form>
            </figure>
        </div>
        {% endfor %}
        </div>
  {% else %}
    <h1>Il n'y aucun substitut pour ce produit !</h1>
  {% endif %}
{% endblock %}
</div>
</body>
</html>